spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: game-api
          uri: lb://game-api
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka