spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: game-api
          uri: lb://game-api
          predicates:
            - Path=/api/core/**
          filters:
            - StripPrefix=2
        - id: game-user
          uri: lb://game-user
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1
        - id: game-auth
          uri: lb://game-auth
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1